### ISSUE TITLE
No module named 'models'   from models.common import DetectMultiBackend

### ISSUE THREAD

**Issue by mehulnavalakha99** [abhip07/real-time-pothole-detection#1]
No module named 'models'
  File "C:\Users\..\Desktop\yolo\real-time-pothole-detection-main\real-time-pothole-detection-main\detect.py", line 30, in <module>
    from models.common import DetectMultiBackend

i dont im getting this error

**Comment by abhishekpwr** [comment]
I haven't pushed the complete code that I'v used in this project.

**Comment by mehulnavalakha99** [comment]
This there any chance that we can get complete code?

**Comment by abhishekpwr** [comment]
contact me on abhishekpawar3007@gmail.com
